name: Formatting

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - photon-style
      - proton-style

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
          commit_message: "Clean: Prettified Code!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
